# Generated by Django 3.2.7 on 2021-10-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
